name: formus_digital_challenge
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.2.5 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  bloc: ^8.1.4
  cached_network_image: ^3.3.1
  dio: ^5.4.3+1
  flutter_bloc: ^8.1.5
  get_it: ^7.6.7
  json_annotation: ^4.9.0
  retrofit: ^4.1.0
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  retrofit_generator: ^8.1.0
  build_runner: ^2.4.9
  json_serializable: ^6.8.0
  flutter_flavorizr: ^2.2.3
  flutter_lints: ^2.0.0

flavorizr:
  flavors:
    dev: 
      app:
        name: "Formus Challenge Dev"
      android:
        applicationId: "com.formus.digital.challenge.dev"
      ios:
        bundleId: "com.formus.digital.challenge.dev"
    homo:
      app:
        name: "Formus Challenge Homo"
      android:
        applicationId: "com.formus.digital.challenge.homo"
      ios:
        bundleId: "com.formus.digital.challenge.homo"
    prod: 
      app:
        name: "Formus Challenge"
      android:
        applicationId: "com.formus.digital.challenge"
      ios:
        bundleId: "com.formus.digital.challenge"

flutter:

  uses-material-design: true

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
